"""Turn any XES log plus its LogSpec into the same modelling matrix shape as BPI 2014.

One code path, five logs. The protocol does not change per log; only the four choices in
`log_schemas.py` do, and those were written down before any AUC existed.

The bundle returned here matches what `bpi2014_data.build()` returns closely enough that
the existing evaluate/score machinery runs on it unchanged: `d`, `y_all`, `g_all`, the two
splits, and the admissible / contaminated feature lists.

A note on the encoding anchor, because the two families differ and the difference matters.
BPI 2014 accumulates Rule 2 history up to the incident's OPEN time. The XES logs accumulate
it up to the DECISION time, the first human touch, which is what the protocol actually
specifies ("observable at the moment of assignment"). Open time is the stricter of the two,
since it grants the model less history, so BPI 2014 is if anything under-credited rather
than over-credited. Stated here rather than quietly normalised, because silently changing
BPI 2014 to match would move published numbers for a reason unrelated to any finding.
"""
from __future__ import annotations

import _openmp_first  # noqa: F401  pins threads, must precede every ML import

import os

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from causal_encoding import encode_causal
from log_schemas import BY_SLUG

SEED = 42
SMOOTHING = 20.0
BREACH_MULTIPLIER = 2.0          # identical in form to BPI 2014
SYSTEM_RESOURCES = {"User_1"}    # BPI 2017's automated actor, 148,404 events
CENSOR_MODE = os.environ.get("BPI_CENSOR", "p95")   # "p95" or "threshold"


class Bundle(dict):
    __getattr__ = dict.__getitem__


def _cache(slug, kind):
    return os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "logs_raw", "%s_%s.pkl" % (slug, kind))


def load_cached(slug):
    # These pickles are written by xes_loader from a log this repository downloaded itself
    # and verified by MD5 against the publisher's checksum. They are a local parse cache, not
    # an input from anywhere untrusted, and they are regenerated by re-running the loader.
    # Nothing outside this directory is ever unpickled.
    c, e = _cache(slug, "cases"), _cache(slug, "events")
    if not (os.path.exists(c) and os.path.exists(e)):
        raise FileNotFoundError(
            "No parsed cache for %s. Run xes_loader.load_xes_cases and pickle it first." % slug)
    return pd.read_pickle(c), pd.read_pickle(e)


def build(slug, test_size=0.3, verbose=True):
    spec = BY_SLUG[slug]
    p = print if verbose else (lambda *a, **k: None)
    cases, events = load_cached(slug)
    p("%s: %d cases, %d events" % (spec.name, len(cases), len(events)))

    events = events.sort_values(["case_id", "pos"])

    # ---------------------------------------------------------------- decision point
    # Three shapes, one per log family. Which one applies is declared in the spec and was
    # fixed before any AUC existed; nothing here inspects a score.
    if spec.decision_kind == "first_human_resource":
        sel = events[~events["resource"].isin(SYSTEM_RESOURCES) & events["resource"].notna()]
    elif spec.decision_kind == "after_activity":
        anchor = events[events["activity"] == spec.decision_activity].groupby("case_id")["pos"].min()
        sel = events.join(anchor.rename("anchor_pos"), on="case_id")
        sel = sel[sel["pos"] > sel["anchor_pos"]]
    else:
        sel = events
    first_touch = sel.sort_values(["case_id", "pos"]).groupby("case_id").first()
    d = cases.set_index("case_id").join(
        first_touch[["timestamp", "resource", "activity"]].rename(
            columns={"timestamp": "t_dec", "resource": "group", "activity": "dec_activity"}))
    d["group"] = d["group"].fillna("unknown")
    before = len(d)
    d = d[d["t_dec"].notna()].copy()
    p("  cases with a decision point: %d of %d" % (len(d), before))

    # ---------------------------------------------------------------- outcome
    d["duration_h"] = (d["t_end"] - d["t_open"]).dt.total_seconds() / 3600.0
    sc = getattr(spec, "stratum_col", "") or ""
    if sc and sc in d.columns:
        d["_stratum"] = d[sc].fillna("unknown").astype(str)
    else:
        if sc:
            p("  WARNING: stratum column %r absent, falling back to a global median" % sc)
        d["_stratum"] = "all"
    med = d.groupby("_stratum")["duration_h"].transform("median")
    d["threshold_h"] = BREACH_MULTIPLIER * med
    d = d[d["duration_h"].notna() & d["threshold_h"].notna()].copy()

    # RIGHT-CENSORING GUARD.
    #
    # A duration threshold label is only observable if the case was watched for at least as
    # long as its own threshold. A case opened near the end of the log cannot exceed the
    # threshold no matter how slow it was, so labelling it "no breach" records the log's end
    # date, not the process. Measured before this guard existed, breach rate by quartile of
    # open time on Hospital Billing ran 0.228, 0.248, 0.207, then 0.011. That last quartile is
    # the log ending. It also inflated the admissible AUC to 0.9241, because any feature
    # correlated with the calendar separates it trivially.
    #
    # Cases whose observation window is shorter than their own threshold are therefore
    # dropped as UNLABELLED rather than counted as negatives. On BPI 2014 this removes 147 of
    # 46,605 cases, 0.32 per cent, so the spine is barely affected and the rule is applied
    # uniformly rather than only where it helps.
    # Two arms, both defensible, both reported. CENSOR_MODE selects which is the headline.
    #
    #   "threshold"  keep a case only if it was watched for at least its own threshold. This
    #                is the logical minimum: below it the label is not observable at all.
    #   "p95"        additionally drop cases opened inside a final window as long as the 95th
    #                percentile of duration, so nearly every retained case had time to finish.
    #                Stronger, and the one that actually removes the artifact.
    #
    # Measured on Hospital Billing, breach rate by quartile of open time:
    #   no guard    0.228 0.248 0.207 0.011   <- the last quartile is the log ending
    #   threshold   0.228 0.241 0.230 0.082
    #   p95         0.235 0.219 0.260 0.201   <- flat
    # p95 costs 17,114 of 88,896 cases on that log. Disclosed, not hidden.
    log_end = d["t_end"].max()
    observable_h = (log_end - d["t_open"]).dt.total_seconds() / 3600.0
    labellable = observable_h >= d["threshold_h"]
    n_thr = int((~labellable).sum())
    if CENSOR_MODE == "p95":
        p95 = d["duration_h"].quantile(0.95)
        labellable &= d["t_open"] <= (log_end - pd.Timedelta(hours=float(p95)))
    n_censored = int((~labellable).sum())
    p("  right-censoring guard [%s]: dropped %d of %d (%.2f%%), threshold rule alone would drop %d"
      % (CENSOR_MODE, n_censored, len(d), 100.0 * n_censored / max(len(d), 1), n_thr))
    d = d[labellable].copy()

    y = (d["duration_h"] > d["threshold_h"]).astype(int)
    p("  breach rate: %.4f  strata: %d" % (y.mean(), d["_stratum"].nunique()))

    # ---------------------------------------------------------------- admissible features
    t_dec = d["t_dec"]
    d["Dec_Hour"] = t_dec.dt.hour
    d["Dec_DayOfWeek"] = t_dec.dt.dayofweek
    d["Is_Weekend"] = (d["Dec_DayOfWeek"] >= 5).astype(int)
    d["Is_Business_Hours"] = ((d["Dec_Hour"] >= 8) & (d["Dec_Hour"] <= 18)).astype(int)
    d["Dec_Month"] = t_dec.dt.month
    d["Assignment_Delay_Hours"] = ((t_dec - d["t_open"]).dt.total_seconds() / 3600.0).clip(lower=0)

    # queue at the decision instant, same construction as BPI 2014's corrected version:
    # cases opened before t_dec_i and not observed to have ended by then
    to = d["t_open"].values.astype("datetime64[ns]").astype(np.int64)
    te = d["t_end"].values.astype("datetime64[ns]").astype(np.int64)
    td = t_dec.values.astype("datetime64[ns]").astype(np.int64)
    d["Queue_At_Decision"] = (np.searchsorted(np.sort(to), td, side="left")
                              - np.searchsorted(np.sort(te), td, side="left"))

    static = []
    for col in spec.admissible_case_attrs:
        if col not in d.columns:
            continue
        name = col.replace("case:", "").replace("first:", "") + "_Encoded"
        vals = d[col]
        num = pd.to_numeric(vals, errors="coerce")
        if num.notna().mean() > 0.9:
            d[name] = num.fillna(num.median())
        else:
            d[name] = LabelEncoder().fit_transform(vals.fillna("unknown").astype(str))
        static.append(name)

    BASE_CLEAN = static + ["Dec_Hour", "Dec_DayOfWeek", "Is_Weekend", "Is_Business_Hours",
                           "Dec_Month", "Assignment_Delay_Hours", "Queue_At_Decision"]

    # ---------------------------------------------------------------- Rule 2, exact
    g = d["group"].astype(str)
    theta, cnt = encode_causal(td, te, g.values, y.values, alpha=SMOOTHING)
    d["Group_Breach_Rate_TE"] = theta
    d["Group_Volume_TE"] = cnt
    GROUP_TE = ["Group_Breach_Rate_TE", "Group_Volume_TE"]

    # ---------------------------------------------------------------- inadmissible arm
    ev = events[events["case_id"].isin(d.index)]
    # the XES loader already carries n_events; drop it so the recomputed one does not collide
    d = d.drop(columns=[c for c in ("n_events",) if c in d.columns])
    agg = ev.groupby("case_id").agg(
        n_events=("activity", "size"),
        n_resources_touched=("resource", "nunique"),
        n_activities=("activity", "nunique"))
    d = d.join(agg)
    acts = ev.assign(one=1).pivot_table(index="case_id", columns="activity", values="one",
                                        aggfunc="sum", fill_value=0)
    INADMISSIBLE = ["n_events", "n_resources_touched", "n_activities"]
    for feat in spec.inadmissible_features:
        if feat in INADMISSIBLE:
            continue
        if feat.startswith("first_"):
            # a field written onto the first event but populated retrospectively
            src = "first:" + feat[len("first_"):]
            if src in d.columns:
                v = d[src]
                num = pd.to_numeric(v, errors="coerce")
                d[feat] = num.fillna(0) if num.notna().mean() > 0.9 else \
                    LabelEncoder().fit_transform(v.fillna("unknown").astype(str))
                INADMISSIBLE.append(feat)
            continue
        needle = {"n_offers": "O_Create Offer", "n_workflow_events": "W_",
                  "was_returned": "O_Returned", "was_incomplete": "A_Incomplete"}.get(feat)
        if needle is None:
            continue
        if needle.endswith("_"):
            cols = [c for c in acts.columns if str(c).startswith(needle)]
            d[feat] = acts[cols].sum(axis=1).reindex(d.index).fillna(0) if cols else 0
        else:
            d[feat] = acts[needle].reindex(d.index).fillna(0) if needle in acts.columns else 0
        INADMISSIBLE.append(feat)
    CONTAMINATED = BASE_CLEAN + INADMISSIBLE

    d = d.reset_index()
    y = y.reset_index(drop=True)
    g = g.reset_index(drop=True)
    for c in BASE_CLEAN + GROUP_TE + INADMISSIBLE:
        d[c] = pd.to_numeric(d[c], errors="coerce").fillna(0)

    idx_tr, idx_te = train_test_split(d.index, test_size=test_size, stratify=y, random_state=SEED)
    ds = d.sort_values("t_dec")
    cut = int(len(ds) * 0.8)
    p("  admissible %d, contaminated %d, groups %d"
      % (len(BASE_CLEAN) + len(GROUP_TE), len(CONTAMINATED), g.nunique()))

    return Bundle(spec=spec, d=d, y_all=y, g_all=g,
                  idx_tr=idx_tr, idx_te=idx_te,
                  idx_tr_time=ds.index[:cut], idx_te_time=ds.index[cut:],
                  BASE_CLEAN=BASE_CLEAN, GROUP_TE=GROUP_TE,
                  CONTAMINATED=CONTAMINATED, INADMISSIBLE=INADMISSIBLE)
