"""Generate the manuscript's number tables from the artifacts.

Every table in this paper was hand-typed from a CSV. That is how two defects got in and
survived: a fold mean printed 0.7728 where every artifact says 0.7727, and a standard
deviation printed 0.0051 that matched neither the sample nor the population form. Both sat
inside a verifier tolerance ten times wider than the printed precision, so nothing caught
them. When the dataset was replaced and the protocol corrected, 524 printed numbers went
stale at once, and re-typing 300 of them by hand would have reintroduced the same failure
at a larger scale.

So the tables are generated. Each one is written to `paper/generated/<label>.tex` holding
only the tabular body, and the manuscript keeps its own caption, label and float. That split
matters: the numbers come from the artifacts and cannot drift, while the prose around them
stays a human decision.

    python figures/make_tables.py

Run it after any pipeline change, then rebuild. A table that changes without a run changing
is a bug in this file, not in the paper.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

import pandas as pd

CODE = Path(__file__).resolve().parent.parent
OUT = CODE.parent / "paper" / "generated"
OUT.mkdir(parents=True, exist_ok=True)

R70 = CODE / "results_bpi_leakfree_7030"
R80 = CODE / "results_bpi_leakfree"
DEEP = CODE / "results_deep_7030"
EVAL = CODE / "results_evaluation"
FORM = CODE / "results_formulations"

MADE = []


def _normalise(body):
    """Repair the two malformations that Python escaping keeps producing here.

    Emitting LaTeX from Python string literals is a known trap: a row terminator needs two
    backslashes in the output and therefore four in the source, while a command name needs
    one and therefore two. Getting either wrong produces a file that looks right in a diff
    and fails in the compiler with "Misplaced \noalign". Both malformations are fixed here
    once, so a generator can be written the obvious way and still emit valid LaTeX.
    """
    out = []
    for line in body.split(chr(10)):
        st = line.rstrip()
        # a data row that ends in a single backslash wanted a row break
        if st.endswith(chr(92)) and not st.endswith(chr(92) * 2):
            st = st + chr(92)
        # a doubled thin space is a row break followed by a comma
        st = st.replace(chr(92) * 2 + ",", chr(92) + ",")
        out.append(st)
    return chr(10).join(out)


def write(name, body):
    body = _normalise(body)
    p = OUT / (name + ".tex")
    header = ("%% GENERATED by code/figures/make_tables.py. Do not edit by hand.\n"
              "%% The caption, label and float live in the manuscript; only the numbers are here.\n")
    p.write_text(header + body.rstrip() + "\n", encoding="utf-8", newline="\n")
    MADE.append(name)
    print("  [ok] %-28s %5d bytes" % (name, p.stat().st_size))


def f4(x):
    return "%.4f" % float(x)


def tab_cost():
    m = pd.read_csv(R70 / "model_comparison_leakfree.csv")
    ci = None
    p = DEEP / "bootstrap_ci.csv"
    if p.exists():
        b = pd.read_csv(p)
        ci = {(r.Config, r.Model): (r.CI_low, r.CI_high) for r in b.itertuples()}
    rows = []
    order = ["XGBoost", "LightGBM", "CatBoost", "RandomForest"]
    label = {"RandomForest": "Random forest"}
    for mo in order:
        x = m[m.Model == mo].set_index("Config")["Test_AUC"]
        c, a, t = x["contaminated_v1"], x["leakfree"], x["leakfree_temporal"]
        cost = c - a
        share = 100.0 * cost / (c - 0.5)
        cis = ""
        if ci and ("cost_of_admissibility", mo) in ci:
            lo, hi = ci[("cost_of_admissibility", mo)]
            cis = " [%s, %s]" % (f4(lo), f4(hi))
        bold = (lambda v: r"\textbf{" + f4(v) + "}") if mo == "XGBoost" else f4
        rows.append("%-13s & %s & %s & %s & %s%s & \\SI{%.1f}{\\percent} \\\\"
                    % (label.get(mo, mo), f4(c), bold(a), f4(t), f4(cost), cis, share))
    nf = m.set_index("Config")["Num_Features"].to_dict()
    body = ("\\begin{tabular}{lrrrrr}\n\\toprule\n"
            "Learner & Unconstrained & Admissible & Chronological & Cost (95\\% CI) & Share of signal \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\midrule\n"
            "Attributes   & %d & %d & %d & & \\\\\n\\bottomrule\n\\end{tabular}"
            % (nf.get("contaminated_v1", 20), nf.get("leakfree", 17), nf.get("leakfree_temporal", 17)))
    write("tab_cost", body)


def tab_ladder():
    a = pd.read_csv(R70 / "feature_ladder_leakfree.csv").set_index("Feature_Set")
    b = pd.read_csv(R80 / "feature_ladder_leakfree.csv").set_index("Feature_Set")
    pretty = {"3_static_only": "Static record fields",
              "8_plus_temporal": "+ arrival-time context",
              "10_plus_operational": "+ operational congestion",
              "15_plus_config": "+ configuration and category",
              "17_plus_group_TE": "+ group target encoding"}
    rows = []
    for k in a.index:
        rows.append("%-30s & %d & %s & %s & %s \\\\"
                    % (pretty.get(k, k), int(a.loc[k, "Num_Features"]),
                       f4(a.loc[k, "Test_AUC"]), f4(b.loc[k, "Test_AUC"]),
                       f4(abs(a.loc[k, "Test_AUC"] - b.loc[k, "Test_AUC"]))))
    ga = a.loc["17_plus_group_TE", "Test_AUC"] - a.loc["8_plus_temporal", "Test_AUC"]
    gb = b.loc["17_plus_group_TE", "Test_AUC"] - b.loc["8_plus_temporal", "Test_AUC"]
    body = ("\\begin{tabular}{lrrrr}\n\\toprule\n"
            "Feature set & Attributes & 70/30 AUC & 80/20 AUC & $|\\Delta|$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\midrule\n"
            + "Gain, eight to seventeen & & %s & %s & %s \\\\\n\\bottomrule\n\\end{tabular}"
            % (f4(ga), f4(gb), f4(abs(ga - gb))))
    write("tab_ladder", body)


def tab_crosslog():
    rows = []
    for d in sorted(CODE.glob("results_*")):
        f = d / "summary.json"
        if not f.exists():
            continue
        s = json.loads(f.read_text(encoding="utf-8"))
        rows.append((s["slug"], s["domain"], s["n_cases"], s["n_groups"],
                     s["breach_rate"], s["best_admissible_auc"], s["share_of_signal_pct"]))
    m = pd.read_csv(R70 / "model_comparison_leakfree.csv")
    x = m[m.Model == "XGBoost"].set_index("Config")["Test_AUC"]
    ds = pd.read_csv(DEEP / "dataset_stats.csv").set_index("Property")["Value"]
    # No .get() default on the case count. A default here would silently print a hardcoded
    # number if the key were ever renamed, which is the exact failure this file exists to
    # remove; the key is "Incidents in the modelling matrix" and a KeyError is the right
    # outcome if it moves.
    rows.append(("bpi2014", "IT service management",
                 int(ds["Incidents in the modelling matrix"]),
                 int(ds.get("Distinct first-assignment groups", 0)),
                 float(ds.get("Positive class rate", 0)), x["leakfree"],
                 100.0 * (x["contaminated_v1"] - x["leakfree"]) / (x["contaminated_v1"] - 0.5)))
    name = {"bpi2014": "BPI Challenge 2014", "bpic2017": "BPI Challenge 2017",
            "sepsis": "Sepsis Cases", "hospital": "Hospital Billing",
            "trafficfines": "Road Traffic Fines"}
    rows.sort(key=lambda r: -r[5])
    body = ["\\begin{tabular}{llrrrrr}", "\\toprule",
            "Log & Domain & Cases & Groups & Breach rate & Admissible AUC & Share lost \\\\",
            "\\midrule"]
    for slug, dom, n, g, br, auc, share in rows:
        body.append("%s & %s & %s & %d & %s & %s & \\SI{%.1f}{\\percent} \\\\"
                    % (name.get(slug, slug), dom.split(",")[0], "{:,}".format(n).replace(",", "\\,"),
                       g, f4(br), f4(auc), share))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_crosslog", "\n".join(body))


def tab_mechanism():
    p = CODE / "results_crosslog" / "mechanism_check.csv"
    if not p.exists():
        print("  [skip] tab_mechanism: no mechanism_check.csv")
        return
    d = pd.read_csv(p)
    name = {"bpic2017": "BPI Challenge 2017", "sepsis": "Sepsis Cases",
            "hospital": "Hospital Billing", "trafficfines": "Road Traffic Fines"}
    rows = []
    for r in d.itertuples():
        rows.append("%s & \\SI{%.1f}{\\percent} & \\SI{%.1f}{\\percent} & \\SI{%.1f}{\\percent} \\\\"
                    % (name.get(r.slug, r.slug), r.full_share_pct,
                       getattr(r, "counts_share_pct", float("nan")),
                       getattr(r, "no_counts_share_pct", float("nan"))))
    body = ("\\begin{tabular}{lrrr}\n\\toprule\n"
            "Log & All inadmissible & Event counts only & Excluding counts \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_mechanism", body)


ORDER = ["XGBoost", "LightGBM", "CatBoost", "RandomForest"]
NICE = {"RandomForest": "Random forest"}
CFG = {"contaminated_v1": "Unconstrained", "leakfree": "Admissible",
       "leakfree_temporal": "Chronological"}


def tab_full():
    d = pd.read_csv(DEEP / "full_metrics.csv")
    rows = []
    for cfg in ["contaminated_v1", "leakfree", "leakfree_temporal"]:
        sub = d[d.Config == cfg]
        if sub.empty:
            continue
        for mo in ORDER:
            r = sub[sub.Model == mo]
            if r.empty:
                continue
            r = r.iloc[0]
            cells = [f4(r.Accuracy), f4(r.Precision), f4(r.Recall), f4(r.Specificity),
                     f4(r.F1), f4(r.MCC), f4(r.AUC), f4(r.AveragePrecision), f4(r.Brier)]
            if cfg == "leakfree" and mo == "XGBoost":
                cells = [r"\textbf{" + c + "}" for c in cells]
            rows.append("%s & %-13s & %s \\\\" % (CFG[cfg], NICE.get(mo, mo), " & ".join(cells)))
        rows.append(r"\\midrule")
    if rows and rows[-1] == r"\\midrule":
        rows.pop()
    body = ("\\begin{tabular}{llrrrrrrrrr}\n\\toprule\n"
            "Configuration & Learner & Acc. & Prec. & Rec. & Spec. & $F_1$ & MCC & AUC & AP & Brier \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_full", body)


def tab_confusion():
    d = pd.read_csv(DEEP / "confusion_matrices.csv")
    rows = []
    for cfg in ["contaminated_v1", "leakfree"]:
        sub = d[d.Config == cfg]
        for mo in ORDER:
            r = sub[sub.Model == mo]
            if r.empty:
                continue
            r = r.iloc[0]
            rows.append("%s & %-13s & %d & %d & %d & %d & %s & %s & %s \\\\"
                        % (CFG[cfg], NICE.get(mo, mo), r.TN, r.FP, r.FN, r.TP,
                           f4(r.Specificity), f4(r.NPV), f4(r.MCC)))
        rows.append(r"\\midrule")
    if rows and rows[-1] == r"\\midrule":
        rows.pop()
    body = ("\\begin{tabular}{llrrrrrrr}\n\\toprule\n"
            "Configuration & Learner & TN & FP & FN & TP & Specificity & NPV & MCC \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_confusion", body)


def tab_folds():
    d = pd.read_csv(DEEP / "cv_folds.csv")
    d = d[d.Config == "leakfree"]
    rows = []
    for mo in ORDER:
        s = d[d.Model == mo]["AUC"]
        if s.empty:
            continue
        cells = " & ".join(f4(v) for v in s.tolist()[:5])
        rows.append("%-13s & %s & %s & %s \\\\"
                    % (NICE.get(mo, mo), cells, f4(s.mean()), f4(s.std(ddof=1))))
    body = ("\\begin{tabular}{lrrrrrrr}\n\\toprule\n"
            "Learner & Fold 1 & Fold 2 & Fold 3 & Fold 4 & Fold 5 & Mean & SD \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_folds", body)


def tab_learning():
    d = pd.read_csv(DEEP / "learning_curve.csv")
    rows = ["%s & %d & %s & %s & %s \\\\"
            % (f4(r.Train_fraction), int(r.Train_n), f4(r.Train_AUC), f4(r.Test_AUC), f4(r.Gap))
            for r in d.itertuples()]
    body = ("\\begin{tabular}{rrrrr}\n\\toprule\n"
            "Fraction & Training rows & Training AUC & Held-out AUC & Gap \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_learning", body)


def tab_threshold():
    d = pd.read_csv(DEEP / "threshold_sweep.csv")
    d = d[(d.Threshold * 100).round() % 10 == 0]
    rows = ["%s & %s & %s & %s & %s & %s \\\\"
            % (f4(r.Threshold), f4(r.Precision), f4(r.Recall), f4(r.F1),
               f4(r.Accuracy), f4(r.Flagged_fraction)) for r in d.itertuples()]
    body = ("\\begin{tabular}{rrrrrr}\n\\toprule\n"
            "Threshold & Precision & Recall & $F_1$ & Accuracy & Flagged \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_threshold", body)


def tab_temporal():
    d = pd.read_csv(DEEP / "temporal_metrics.csv")
    rows = []
    for r in d.itertuples():
        rows.append("%-13s & %s & %s & %s & %s & %s & %s \\\\"
                    % (NICE.get(r.Model, r.Model), str(r.Threshold_rule).replace("_", " "),
                       f4(r.Threshold), f4(r.AUC), f4(r.Precision), f4(r.Recall), f4(r.F1)))
    body = ("\\begin{tabular}{llrrrrr}\n\\toprule\n"
            "Learner & Threshold rule & Cut & AUC & Precision & Recall & $F_1$ \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_temporal", body)


def tab_dataset():
    d = pd.read_csv(DEEP / "dataset_stats.csv")
    rows = []
    for r in d.itertuples():
        v = str(r.Value)
        try:
            fv = float(v)
            v = "{:,}".format(int(fv)).replace(",", "\\,") if fv == int(fv) and abs(fv) >= 1 else f4(fv)
        except ValueError:
            pass
        rows.append("%s & %s \\\\" % (str(r.Property).replace("&", "and"), v))
    body = ("\\begin{tabular}{lr}\n\\toprule\n"
            "Property & Value \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_dataset", body)


POLICY_NAME = {"Random": "Random", "RoundRobin": "Round robin", "FIFO": "FIFO",
               "LeastLoaded": "Least loaded", "GreedyBestOutcome": "Greedy best outcome",
               "StandardNSGA2": "Standard NSGA-II", "NSGA3": "NSGA-III",
               "PAA-NSGA-II": "PAA-NSGA-II", "PAA-noPriority": "PAA without priority init",
               "PAA-noAdaptive": "PAA without adaptive crossover",
               "PAA-noSLAMut": "PAA without SLA mutation",
               "PAA-AdaptMut": "PAA with adaptive mutation",
               "NSGA3-PrioInit": "NSGA-III + priority init"}


def _n(v, dp=4):
    try:
        f = float(v)
    except (TypeError, ValueError):
        return "--"
    if f != f:
        return "--"
    return ("%." + str(dp) + "f") % f


def tab_assignment():
    d = pd.read_csv(EVAL / "policy_means.csv")
    cols = [c for c in ["hypervolume", "f1_ftr", "f2_breach", "f3_workload_sd", "f4_expertise"]
            if c in d.columns]
    rows = []
    for r in d.itertuples():
        vals = " & ".join(_n(getattr(r, c)) for c in cols)
        rows.append("%-30s & %s \\\\" % (POLICY_NAME.get(r.policy, r.policy), vals))
    head = "Policy & " + " & ".join(
        {"hypervolume": "Hypervolume", "f1_ftr": "$f_1$ FTR", "f2_breach": "$f_2$ breach",
         "f3_workload_sd": "$f_3$ workload SD", "f4_expertise": "$f_4$ expertise"}[c]
        for c in cols) + " \\\\"
    body = ("\\begin{tabular}{l" + "r" * len(cols) + "}\n\\toprule\n" + head + "\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_assignment", body)


def tab_runtime():
    d = pd.read_csv(EVAL / "runtime.csv")
    rows = ["%-30s & %s & %s & %d & %s \\\\"
            % (POLICY_NAME.get(r.policy, r.policy), _n(r.mean_s_per_solve, 2),
               _n(r.sd_s, 2), int(r.solves), _n(r.pct_vs_standard_nsga2, 1))
            for r in d.itertuples()]
    body = ("\\begin{tabular}{lrrrr}\n\\toprule\n"
            "Policy & Mean s/solve & SD & Solves & Percent vs NSGA-II \\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_runtime", body)


def tab_weights():
    d = pd.read_csv(FORM / "weights.csv")
    rows = ["%-14s & %s & %s & %s \\\\"
            % (str(r.criterion).replace("_", " "), _n(r.critic), _n(r.entropy), _n(r.equal))
            for r in d.itertuples()]
    body = ("\\begin{tabular}{lrrr}\n\\toprule\n"
            "Criterion & CRITIC & Entropy & Equal \\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_weights", body)


def tab_psweep():
    d = pd.read_csv(FORM / "p_sweep.csv")
    rows = ["%s & %s & %s & %s & %d \\\\"
            % (_n(r.p, 1), _n(r.mean), _n(r.min), _n(r.max), int(r.exact_zero_cells))
            for r in d.itertuples()]
    body = ("\\begin{tabular}{rrrrr}\n\\toprule\n"
            "$p$ & Mean score & Min & Max & Exact zeros \\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_psweep", body)


def tab_priority():
    d = pd.read_csv(DEEP / "priority_breakdown.csv")
    rows = ["%d & %s & %s & %s & %s \\\\"
            % (int(r.Priority), "{:,}".format(int(r.n)).replace(",", "\\\\,"),
               _n(r.median_handle_hours, 2), _n(r.threshold_hours, 2), _n(r.breach_rate))
            for r in d.itertuples()]
    body = ("\\begin{tabular}{rrrrr}\n\\toprule\n"
            "Priority & Cases & Median hours & Threshold hours & Breach rate \\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_priority", body)


CRITERION_LABEL = {
    "s1_outcome": ("$s_1$", "Outcome propensity"),
    "s2_sla_survival": ("$s_2$", "Service level survival"),
    "s3_expertise": ("$s_3$", "Expertise match"),
    "s4_workload": ("$s_4$", "Workload headroom"),
    "s5_freshness": ("$s_5$", "Freshness"),
    "s6_urgency": ("$s_6$", "Urgency"),
    "s7_importance": ("$s_7$", "Importance"),
}


def _fitted():
    return json.loads((FORM / "fitted_parameters.json").read_text(encoding="utf-8"))


def _hazard():
    return json.loads((FORM / "hazard_model.json").read_text(encoding="utf-8"))


def _small(x, dp=4):
    """Print a number that would round to a row of zeros in scientific form instead."""
    v = float(x)
    if v != 0.0 and abs(v) < 10.0 ** (-dp):
        return "$\\num{%.1e}$" % v
    return "%.*f" % (dp, v)


def _thousands(x):
    return "\\num{%d}" % int(round(float(x)))


def tab_fitted():
    """Every fitted constant in F1 and F2, with its interval and its support.

    This table was hand-typed and every row of it went stale at once when the dataset was
    replaced and the date parse corrected. Half of the rows are derived quantities (an
    implied half-life, a percentage of a count) that were computed once with a calculator
    and never again, which is the exact failure mode the generated tables exist to remove.
    """
    import math

    f = _fitted()
    lam, urg, exp = f["s5_freshness_decay"], f["s6_urgency_ramp"], f["s3_expertise"]
    hz = _hazard()
    cells = int(exp["eval_shape"][0]) * int(exp["eval_shape"][1])
    half_life = math.log(2.0) / lam["lambda_per_hour"]
    # The tuning note reads "...(earliest 80 per cent) (f1 = 0.5134)". Pull the value that
    # follows "f1 =" rather than the last number in the string, so the 80 in "80 per cent"
    # can never be mistaken for it.
    thr_f1 = ""
    mt = re.search(r"f1\s*=\s*([0-9.]+)", str(hz.get("threshold_tuned_on", "")), re.I)
    if mt:
        thr_f1 = ", $F_1=\\num{%s}$" % mt.group(1)

    rows = [
        "$\\hat{\\lambda}$ & Freshness decay rate, per hour & %s & [%s, %s], $n=\\num{%d}$ \\\\"
        % (_small(lam["lambda_per_hour"]), _small(lam["ci95"][0]), _small(lam["ci95"][1]),
           int(lam["n"])),
        " & \\quad implied half-life (hours) & %.1f & derived from $\\hat{\\lambda}$ \\\\"
        % half_life,
        "$\\hat{k}$ & Urgency ramp steepness & %s & $n=\\num{%d}$ \\\\"
        % (_small(urg["k"]), int(urg["n"])),
        "$\\hat{\\tau}_0$ & Urgency ramp midpoint, hours & $%.2f$ & $n=\\num{%d}$ \\\\"
        % (urg["tau0_hours"], int(urg["n"])),
        "$\\varepsilon$ & Floor applied before any $p\\le0$ aggregation & $10^{-3}$ & fixed, reported as a parameter \\\\",
        "$\\alpha$ & Target-encoding smoothing prior & 20 & fixed \\\\",
        "$\\hat{\\theta}$ & F2 escalation cut point & %s & tuned on train%s \\\\"
        % (_small(hz["threshold"]), thr_f1),
        "\\midrule",
        " & Cosine-expertise cells evaluated & %s & $\\num{%d}\\times\\num{%d}$ \\\\"
        % (_thousands(cells), int(exp["eval_shape"][0]), int(exp["eval_shape"][1])),
        " & \\quad of which exactly zero & %s & \\SI{%.2f}{\\percent} \\\\"
        % (_thousands(exp["exact_zero_cells"]), 100.0 * float(exp["exact_zero_fraction"])),
        " & Delay rows above the \\num{%d}\\,h cap & %s & \\SI{%.1f}{\\percent} of \\num{%d}, a modelling choice \\\\"
        % (int(lam["delay_cap_hours"]), _thousands(lam["rows_excluded_above_cap"]),
           100.0 * float(lam["excluded_fraction"]), int(lam["finite_delay_rows"])),
    ]
    body = ("\\begin{tabular}{lL{5.1cm}rl}\n\\toprule\n"
            "Symbol & Quantity & Estimate & Interval / support \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_fitted", body)


TUNING_LABEL = [
    ("XGBoost_untuned", "XGBoost, untuned", None),
    ("LightGBM_untuned", "LightGBM, untuned", None),
    ("CatBoost_untuned", "CatBoost, untuned", None),
    ("RandomForest_untuned", "Random forest, untuned", None),
    (None, None, None),                                   # \midrule
    ("XGBoost_tuned", "XGBoost, tuned", "XGBoost_tuned"),
    ("LightGBM_tuned", "LightGBM, tuned", "LightGBM_tuned"),
    ("SoftVote(XGBt,LGBMt,CatBoost)", "Soft vote, 3 models", "SoftVote_3"),
    ("SoftVote(4 models)", "Soft vote, 4 models", "SoftVote_4"),
    ("Stacking(LR meta)", "Stacking, logistic meta", "Stacking"),
]


ABLATION_ROWS = [
    ("PAA-noPriority", "Priority-aware initialisation"),
    ("PAA-noAdaptive", "Adaptive crossover"),
    ("PAA-noSLAMut", "SLA-aware mutation"),
]


def tab_ablation():
    """Component ablation, as a difference against the full method.

    The hand-typed version of this table survived the hypervolume reference-point fix
    unchanged, so it still printed values on the old reference scale: 0.4842 where the
    current run says 0.0782, a factor of six. Both the level and the sign of one delta were
    wrong. Deltas are recomputed here rather than copied, so the arithmetic cannot drift
    from the levels beside it.
    """
    d = pd.read_csv(EVAL / "policy_means.csv").set_index("policy")["hypervolume"]
    full = float(d["PAA-NSGA-II"])
    rows = []
    for key, label in ABLATION_ROWS:
        v = float(d[key])
        rows.append("%-30s & %s & $%+.4f$ \\\\" % (label, f4(v), v - full))
    body = ("\\begin{tabular}{lrr}\n\\toprule\n"
            "Component removed & Hypervolume without & $\\Delta$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\midrule\n"
            + "%-30s & %s & \\\\\n\\bottomrule\n\\end{tabular}"
            % ("None (full method)", f4(full)))
    write("tab_ablation", body)


def tab_tuning():
    """Tuning and ensembling on the admissible feature set.

    The last hand-typed numeric table in the manuscript, and the most stale: all nine rows
    still carried pre-correction values, including a significance column that said two of the
    five gains were indistinguishable from zero when the current run says all five clear it.
    Both the metrics and the significance verdict are read from the artifacts here, so the
    verdict column can no longer disagree with the interval it is supposed to summarise.
    """
    d = pd.read_csv(R70 / "model_b_tuned_ensemble.csv").set_index("Model")
    sg = pd.read_csv(R70 / "model_b_significance.csv").set_index("Model")

    def best(col, keys):
        vals = {k: float(d.loc[k, col]) for k in keys if k in d.index}
        if not vals:
            return None
        return (min if col == "Brier" else max)(vals, key=vals.get)

    keys = [k for k, _, _ in TUNING_LABEL if k]
    bold_of = {c: best(c, keys) for c in
               ["Test_AUC", "Accuracy", "Precision", "Recall", "F1", "Brier"]}

    def cell(k, col):
        v = f4(d.loc[k, col])
        return "\\textbf{" + v + "}" if bold_of.get(col) == k else v

    rows = []
    for key, label, sig_key in TUNING_LABEL:
        if key is None:
            rows.append("\\midrule")
            continue
        if key not in d.index:
            continue
        delta, verdict = "---", "---"
        if sig_key and sig_key in sg.index:
            dv = float(sg.loc[sig_key, "Diff_vs_untuned"])
            delta = "$%+.4f$" % dv
            verdict = "yes" if bool(sg.loc[sig_key, "Significant"]) else "no"
        rows.append("%-22s & %s & %s & %s & %s & %s & %s & %s & %s \\\\"
                    % (label, cell(key, "Test_AUC"), cell(key, "Accuracy"),
                       cell(key, "Precision"), cell(key, "Recall"), cell(key, "F1"),
                       cell(key, "Brier"), delta, verdict))
    body = ("\\begin{tabular}{lrrrrrrrc}\n\\toprule\n"
            "Model & AUC & Acc. & Prec. & Rec. & $F_1$ & Brier & $\\Delta$ AUC & Sig. \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_tuning", body)


RELATED_LITERATURE = [
    ("kaufman2012leakage", "Formalises leakage and the learn-predict separation", "Several", "---",
     "States the condition; does not measure what enforcing it costs"),
    ("kapoor2023leakage", "Eight-type leakage taxonomy across 17 fields", "294 papers", "---",
     "Survey of consequences, not a measurement on one log"),
    ("abb2024discussion", "Measures example leakage in process mining", "Standard BPIC logs",
     "$>\\SI{80}{\\percent}$ example leakage",
     "Measures the split axis; does not price the feature axis"),
    ("mishra2026taxonomy", "Removes leaky features from build prediction", "CI build logs",
     "$-15.07$ accuracy points", "Different domain; no benefit side reported"),
    ("weytjens2022creating", "Leak-free benchmark construction", "Process logs", "---",
     "Prescribes the constraint rather than costing it"),
    ("teinemaa2019outcome", "Outcome-prediction benchmark", "24 event logs", "---",
     "BPI 2014 not among the datasets"),
    ("dees2014predictive", "Workload impact analysis on this log", "BPI 2014", "---",
     "Descriptive; no decision-time constraint"),
    ("gouryraj2021service", "Service level breach prediction", "ITSM tickets", "---",
     "No admissibility constraint stated"),
    ("arain2026novel", "Multi-objective ticket assignment", "ITSM", "---",
     "No leakage control on the objective models"),
    ("debjain2014evolutionary", "NSGA-III for many-objective problems", "Benchmarks", "---",
     "Not applied to assignment under admissibility"),
]


LOG_ORDER = ["bpi2014", "bpic2017", "sepsis", "hospital", "trafficfines"]
LOG_SHORT = {"bpi2014": "BPI Challenge 2014", "bpic2017": "BPI Challenge 2017",
             "sepsis": "Sepsis Cases", "hospital": "Hospital Billing",
             "trafficfines": "Road Traffic Fines"}


def tab_logspec():
    """The per-log specification, printed from the file that the code executes.

    The paper claims the decision point, the label and the admissible/inadmissible split were
    fixed for every log before any score was computed on it. A reader has no way to check that
    from prose, and prose is also where it would silently drift away from the code. This table
    is read out of code/log_schemas.py itself, so what the paper shows and what the runner
    obeys are the same object.
    """
    import sys

    if str(CODE) not in sys.path:
        sys.path.insert(0, str(CODE))
    import log_schemas as mod

    def esc(s):
        return (str(s).replace("&", "\\&").replace("_", "\\_")
                .replace("%", "\\%").replace("#", "\\#"))

    def first_sentence(s):
        """The definition, without the paragraphs of rationale that follow it.

        Two of these fields carry several hundred words explaining why a decision point was
        chosen and which obvious alternative was rejected. That belongs in the schema file,
        which a reader can open, and not in a table cell. The caption says where the rest is.
        """
        s = " ".join(str(s).split())
        cut = s.find(". ")
        return s if cut < 0 else s[:cut + 1]

    rows = []
    for slug in LOG_ORDER:
        s = mod.BY_SLUG.get(slug)
        if s is None:
            continue
        n_adm = len(s.admissible_case_attrs)
        n_inadm = len(s.inadmissible_features)
        j = CODE / ("results_%s" % slug) / "summary.json"
        if j.exists():
            d = json.loads(j.read_text(encoding="utf-8"))
            n_adm, n_inadm = int(d["n_admissible"]), int(d["n_inadmissible"])
        rows.append("%s & %s & %s & %s & %d / %d \\\\"
                    % (LOG_SHORT.get(slug, slug), esc(first_sentence(s.decision_point)),
                       esc(first_sentence(s.outcome)), esc(first_sentence(s.group)),
                       n_adm, n_inadm))
    body = ("\\begin{tabular}{L{2.5cm} L{4.0cm} L{3.6cm} L{2.4cm} r}\n\\toprule\n"
            "Log & Decision point $t_{\\mathrm{dec}}$ & Outcome & Rule 2 key & Adm. / inadm. \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_logspec", body)


def tab_related():
    """The related-work table, literature rows included.

    Only the three "This work" rows carry numbers, and they were the last hand-typed copy of
    figures that appear in four other places: all three still read the pre-correction case
    count long after every other table had moved.

    The literature rows are carried here rather than left in the manuscript for a mechanical
    reason. Emitting only the three numeric rows and \\input-ing them INSIDE the tabular
    fails: TeX is mid-alignment when it opens the file, and the row boundary is lost, so the
    \\bottomrule that follows lands inside a cell and both drivers stop with "Misplaced
    \\noalign". Every other generated table replaces a whole tabular, which is the shape that
    works, so this one does the same. The citations are static text and carry no numbers.
    """
    m = pd.read_csv(R70 / "model_comparison_leakfree.csv")
    x = m[m.Model == "XGBoost"].set_index("Config")["Test_AUC"]
    ds = pd.read_csv(DEEP / "dataset_stats.csv").set_index("Property")["Value"]
    n = int(ds["Incidents in the modelling matrix"])
    cases = "BPI 2014, \\num{%d}" % n

    rows = ["\\citet{%s} & %s & %s & %s & %s \\\\" % r for r in RELATED_LITERATURE]
    rows.append("\\midrule")
    rows += [
        "\\textbf{This work, unconstrained} & Reproduction of the default practice & %s & %s AUC & Reported only to size the correction \\\\"
        % (cases, f4(x["contaminated_v1"])),
        "\\textbf{This work, admissible} & Rules 1 and 2 enforced & %s & \\textbf{%s} AUC & The deployable figure \\\\"
        % (cases, f4(x["leakfree"])),
        "\\textbf{This work, chronological} & Admissible, evaluated forward in time & %s & %s AUC & The figure under drift \\\\"
        % (cases, f4(x["leakfree_temporal"])),
    ]
    body = ("\\begin{tabular}{L{3.15cm} L{3.0cm} L{2.35cm} L{2.1cm} L{3.35cm}}\n\\toprule\n"
            "Study & Approach & Data & Reported & Limitation for this question \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_related", body)


def tab_criteria():
    """Spread of each criterion over the evaluation-period decision matrix."""
    d = pd.read_csv(FORM / "decision_matrix_stats.csv")
    rows = []
    for r in d.itertuples():
        sym, name = CRITERION_LABEL.get(r.criterion, ("", str(r.criterion).replace("_", " ")))
        zeros = "0" if int(r.exact_zeros) == 0 else _thousands(r.exact_zeros)
        rows.append("%-6s & %-24s & %s & %s & %s & %s & %.3f \\\\"
                    % (sym, name, _small(r.mean), _small(r.std), _small(r.min),
                       zeros, float(r.critic_conflict)))
    body = ("\\begin{tabular}{llrrrrr}\n\\toprule\n"
            " & Criterion & Mean & SD & Min & Exact zeros & Conflict \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_criteria", body)


def tab_hazard():
    """F2: the four models of the same process, including the one that is rejected.

    The rejected row's AUC was a hardcoded literal until 2026-09-07, in a paper whose whole
    subject is claims that fail verification. It is now measured in the same run, with the
    same features and the same split, changing only the event definition.
    """
    hz = _hazard()
    rows = [
        "Direct breach classifier & %s & $P(\\text{breach} \\mid \\mathbf{x})$ at intake \\\\"
        % _small(hz["static_model_breach_auc_for_comparison"]),
        "Resolution hazard, bin level & %s & $h(t \\mid \\mathbf{x})$ per person-period row \\\\"
        % _small(hz["heldout_resolution_hazard_auc"]),
        "Breach derived from resolution, at intake & \\textbf{%s} & $S(\\tau\\mid\\mathbf{x})/S(t\\mid\\mathbf{x})$ \\\\"
        % _small(hz["derived_breach_auc_at_intake"]),
        "\\midrule",
        "Breach hazard with elapsed time (rejected) & %s & reads its own label \\\\"
        % _small(hz["rejected_breach_hazard_auc"]),
    ]
    body = ("\\begin{tabular}{lrl}\n\\toprule\n"
            "Model & Held-out AUC & What it estimates \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    write("tab_hazard", body)


if __name__ == "__main__":
    print("generating tables from artifacts")
    for fn in (tab_cost, tab_ladder, tab_crosslog, tab_mechanism,
               tab_full, tab_confusion, tab_folds, tab_learning,
               tab_threshold, tab_temporal, tab_dataset,
               tab_assignment, tab_runtime, tab_weights,
               tab_psweep, tab_priority,
               tab_fitted, tab_criteria, tab_hazard, tab_related,
               tab_tuning, tab_ablation, tab_logspec):
        try:
            fn()
        except Exception as e:
            print("  [FAIL] %-22s %s" % (fn.__name__, str(e)[:70]))
    print("  %d table(s) written to %s" % (len(MADE), OUT))
